// userList constants
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_DELETE = "USER_LIST_DELETE";
export const USER_LIST_CREATE = "USER_LIST_CREATE";
export const USER_LIST_UPDATE = "USER_LIST_UPDATE";

// userDetail constants
export const USER_DETAIL_SUCCESS = "USER_DETAIL_SUCCESS";
export const USER_DETAIL_FAIL = "USER_DETAIL_FAIL";
export const USER_DETAIL_DELETE = "USER_DETAIL_DELETE";
export const USER_DETAIL_CREATE = "USER_DETAIL_CREATE";
export const USER_DETAIL_UPDATE = "USER_DETAIL_UPDATE";
